---
- hosts: local
  become: true

  pre_tasks:
    - name: Add User to Sudoers Group
      user:
        name: "{{ ansible_env.SUDO_USER }}"
        groups: sudo
        append: yes

  roles:
    - { role: install, tags: ['role_install'] }
    - { role: config, tags: ['role_config'] }