---
- hosts: 127.0.0.1
  become: true
  
  roles:
    - role: install
      tags: role_install

    - role: config
      vars:
        hostname: legion5i
        git_name: "Rodrigo Martins"
        git_mail: "rodrigomartins.tic@gmail.com"
      tags: role_config