---
# vars file for config

config_files:
- src: .bash_aliases
  dest: /home/{{ ansible_env.SUDO_USER }}/.bashrc.d
- src: aliases.zsh
  dest: /home/{{ ansible_env.SUDO_USER }}/.oh-my-zsh/custom
- src: .vimrc
  dest: /home/{{ ansible_env.SUDO_USER }}
- src: .tmux.conf
  dest: /home/{{ ansible_env.SUDO_USER }}
- src: .digrc
  dest: /home/{{ ansible_env.SUDO_USER }}

url_fonts:
- url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf
  name: "MesloLGS NF Regular"
- url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf
  name: "MesloLGS NF Bold"
- url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf
  name: "MesloLGS NF Italic"
- url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf
  name: "MesloLGS NF Bold Italic"