---
- name: Copy Custom Config Files to Home Directory
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: 0644
  loop: "{{ config_files }}"

- name: Create Fonts Directory
  ansible.builtin.file:
    path: "/home/{{ ansible_env.SUDO_USER }}/.fonts"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: 0755
    state: directory

- name: Download MesloLGS Fonts
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "/home/{{ ansible_env.SUDO_USER }}/.fonts/{{ item.name }}"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: 0644
  loop: "{{ url_fonts }}"

- name: Load MesloLGS Fonts
  ansible.builtin.shell: >
    fc-cache -f "/home/{{ ansible_env.SUDO_USER }}/.fonts"

- name: Create Wallpaper Directory 
  ansible.builtin.file:
    path: "/home/{{ ansible_env.SUDO_USER }}/Imagens/Wallpapers"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: 0755
    state: directory

- name: Copy Pictures to ~/Imagens/Wallpapers
  ansible.builtin.copy:
    src: root.png
    dest: "/home/{{ ansible_env.SUDO_USER }}/Imagens/Wallpapers/root.png"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: 0644

- name: Set Default Wallpaper
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  become_user: "{{ ansible_env.SUDO_USER }}"
  loop: "{{ wallpaper }}"

- name: Install ZSH Theme Powerlevel10k
  ansible.builtin.command: git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "/home/{{ ansible_env.SUDO_USER }}/powerlevel10k"
  become_user: "{{ ansible_env.SUDO_USER }}"