---
- name: Copy Custom Config Files to Home Directory
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: 0644
  loop: "{{ config_files }}"

- name: Install ZSH Theme Powerlevel10k
  command: git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "/home/{{ ansible_env.SUDO_USER }}/powerlevel10k"
  become_user: "{{ ansible_env.SUDO_USER }}"

- name: Create Wallpaper Directory 
  file:
    path: "/home/{{ ansible_env.SUDO_USER }}/Imagens/Wallpapers"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: 0755
    state: directory

- name: Copy Pictures to ~/Imagens/Wallpapers
  copy:
    src: root.png
    dest: "/home/{{ ansible_env.SUDO_USER }}/Imagens/Wallpapers/root.png"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: 0644

- name: Set Default Wallpaper
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  become_user: "{{ ansible_env.SUDO_USER }}"
  loop: "{{ wallpaper }}"

- name: Extract fonts.tar.gz
  unarchive:
    src: fonts.tar.gz
    dest: "/home/{{ ansible_env.SUDO_USER }}/.local/share/fonts"
  become_user: "{{ ansible_env.SUDO_USER }}"

- name: Reload Fonts
  command: fc-cache -vfs "/home/{{ ansible_env.SUDO_USER }}/.local/share/fonts/"