---
- name: Set Hostname
  ansible.builtin.command: hostnamectl hostname "{{ hostname }}"

- name: Creating Directories
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: '0755'
    state: directory
  loop:
    - "/home/{{ ansible_env.SUDO_USER }}/.bashrc.d"
    - "/home/{{ ansible_env.SUDO_USER }}/.fonts"
    - "/home/{{ ansible_env.SUDO_USER }}/Imagens/Wallpapers"

- name: Update /etc/dnf/dnf.conf
  ansible.builtin.copy:
    src: dnf.conf
    dest: /etc/dnf
    owner: root
    group: root
    mode: '0644'

- name: Copy Custom Config Files to Home Directory
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: '0644'
  loop: "{{ config_files }}"

- name: Copy .gitconfig
  ansible.builtin.template:
    src: .gitconfig.j2
    dest: "/home/{{ ansible_env.SUDO_USER }}/.gitconfig"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: '0644'

- name: Copy automatic.conf
  ansible.builtin.template:
    src: automatic.conf.j2
    dest: /etc/dnf/automatic.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - Enable dnf-automatic.timer

- name: Copy Pictures to ~/Imagens/Wallpapers
  ansible.builtin.copy:
    src: root.png
    dest: "/home/{{ ansible_env.SUDO_USER }}/Imagens/Wallpapers/root.png"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: '0644'

- name: Download MesloLGS Fonts
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "/home/{{ ansible_env.SUDO_USER }}/.fonts/{{ item.name }}"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: '0644'
  loop: "{{ url_fonts }}"

- name: Set Default Wallpaper
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  become_user: "{{ ansible_env.SUDO_USER }}"
  loop: "{{ wallpaper }}"

- name: Load MesloLGS Fonts
  ansible.builtin.shell: >
    fc-cache -f "/home/{{ ansible_env.SUDO_USER }}/.fonts"