---
# vars file for install

remove_pkgs:
  - gnome-calendar
  - gnome-contacts
  - gnome-maps
  - gnome-weather
  - libreoffice*

pkgs_rpm:
  - url: "{{ url_rpm_etcher.stdout }}"
    name: etcher.x86_64.rpm
  - url: https://download.teamviewer.com/download/linux/teamviewer.x86_64.rpm
    name: teamviewer.x86_64.rpm 

pkgs:
  - ansible-core
  - calibre
  - '@container-management'
  - curl
  - enpass
  - flameshot
  - gimp
  - gnome-tweaks
  - google-chrome-stable
  - gparted
  - HandBrake-gui
  - htop
  - ImageMagick
  - jq
  - openfortivpn
  - openssh-server
  - p7zip
  - p7zip-plugins
  - peek
  - qbittorrent
  - tmux
  - tree
  - uget
  - vim-enhanced
  - VirtualBox
  - xclip
  - youtube-dl
  - zsh

flatpak_pkgs:
  - com.discordapp.Discord
  - com.getpostman.Postman
  - com.obsproject.Studio
  - com.visualstudio.code
  - com.slack.Slack
  - in.srev.guiscrcpy
  - io.dbeaver.DBeaverCommunity
  - io.github.celluloid_player.Celluloid
  - io.typora.Typora
  - net.ankiweb.Anki
  - org.onlyoffice.desktopeditors