---
# vars file for install

repo:
  - fedora-workstation-repositories
  - https://yum.enpass.io/enpass-yum.repo

remove_pkgs:
  - gnome-calendar
  - gnome-contacts
  - gnome-maps
  - gnome-weather
  - libreoffice*

pkgs_urls:
  - "{{ url_rpm_etcher.stdout }}" #BalenaEtcher
  - https://download.teamviewer.com/download/linux/teamviewer.x86_64.rpm #TeamViewer

pkgs:
  - anki
  - autokey-common
  - autokey-gtk
  - calibre
  - curl
  - @Development tools
  - enpass
  - flameshot
  - gimp
  - google-chrome-stable
  - gparted
  - handbrake
  - htop
  - imagemagick
  - jq
  - openssh-server
  - p7zip
  - p7zip-plugins
  - peek
  - qbittorrent
  - tmux
  - uget
  - vim
  - xclip
  - youtube-dl
  - zsh

flatpak_pkgs:
  - io.github.celluloid_player.Celluloid
  - com.visualstudio.code
  - com.discordapp.Discord
  - com.wps.Office
  - com.getpostman.Postman
  - com.obsproject.Studio
  - com.valvesoftware.Steam
  - io.typora.Typora
