---
# vars file for install

repo_extra_dnf:
  - repo: fedora-workstation-repositories
    disable_gpg_check: no
  - repo: "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm"
    disable_gpg_check: yes
  - repo: "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm"
    disable_gpg_check: yes
  - repo: https://dl.k6.io/rpm/repo.rpm
    disable_gpg_check: yes

repo_extra_url:
  - repo: https://download.docker.com/linux/fedora/docker-ce.repo
    path: /etc/yum.repos.d/docker-ce.repo
  - repo: https://yum.enpass.io/enpass-yum.repo
    path: /etc/yum.repos.d/enpass-yum.repo
  - repo: https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
    path: /etc/yum.repos.d/hashicorp.repo

remove_pkgs:
  - gnome-boxes
  - gnome-calendar
  - gnome-contacts
  - gnome-maps
  - gnome-tour
  - libreoffice*
  - mediawriter
  - rhythmbox

pkgs_rpm:
  - url: "{{ url_rpm_etcher.stdout }}"
    name: etcher.x86_64.rpm
  - url: https://download.teamviewer.com/download/linux/teamviewer.x86_64.rpm
    name: teamviewer.x86_64.rpm 

pkgs:
  - ansible-core
  - calibre
  - containerd.io
  - curl
  - dnf-automatic
  - dnf-plugins-core
  - docker-ce
  - docker-ce-cli
  - docker-compose-plugin
  - enpass
  - flameshot
  - gimp
  - gnome-tweaks
  - google-chrome-stable
  - gparted
  - htop
  - ImageMagick
  - jq
  - NetworkManager-fortisslvpn
  - NetworkManager-fortisslvpn-gnome
  - openfortivpn
  - openssh-server
  - p7zip
  - p7zip-plugins
  - packer
  - qbittorrent
  - terraform
  - timeshift
  - tmux
  - tree
  - vim
  - VirtualBox
  - xclip
  - yt-dlp
  - zsh

flatpak_pkgs:
  - com.visualstudio.code
  - com.discordapp.Discord
  - com.getpostman.Postman
  - com.wps.Office
  - com.slack.Slack
  - com.obsproject.Studio
  - net.ankiweb.Anki
  - net.agalwood.Motrix
  - net.davidotek.pupgui2
  - io.github.celluloid_player.Celluloid
  - io.dbeaver.DBeaverCommunity
  - in.srev.guiscrcpy