---
# vars file for install

remove_pkgs:
  - gnome-calendar
  - gnome-contacts
  - gnome-maps
  - gnome-weather
  - libreoffice*

pkgs_rpm:
  - url: "{{ url_rpm_etcher.stdout }}"
    name: etcher.x86_64.rpm
  - url: https://download.teamviewer.com/download/linux/teamviewer.x86_64.rpm
    name: teamviewer.x86_64.rpm 

pkgs:
  - anki
  - autokey-common
  - autokey-gtk
  - calibre
  - curl
  - '@Development tools'
  - enpass
  - flameshot
  - gimp
  - gnome-tweaks
  - google-chrome-stable
  - gparted
  - htop
  - ImageMagick
  - jq
  - openssh-server
  - p7zip
  - p7zip-plugins
  - peek
  - qbittorrent
  - tmux
  - uget
  - vim
  - xclip
  - youtube-dl
  - zsh

flatpak_pkgs:
  - io.github.celluloid_player.Celluloid
  - com.visualstudio.code
  - com.discordapp.Discord
  - fr.handbrake.ghb
  - com.wps.Office
  - com.getpostman.Postman
  - com.obsproject.Studio
  - com.valvesoftware.Steam
  - io.typora.Typora
