---
# vars file for install

repo_extra_dnf:
  - repo: fedora-workstation-repositories
    disable_gpg_check: no
  - repo: "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm"
    disable_gpg_check: yes
  - repo: "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm"
    disable_gpg_check: yes

remove_pkgs:
  - gnome-boxes
  - gnome-contacts
  - gnome-maps
  - gnome-tour
  - libreoffice*
  - rhythmbox

pkgs_rpm:
  - url: "{{ url_rpm_etcher.stdout }}"
    name: etcher.x86_64.rpm

pkgs:
  - akmod-nvidia
  - calibre
  - curl
  - dnf-plugins-core
  - flameshot
  - gimp
  - gnome-extensions-app
  - gparted
  - htop
  - ImageMagick
  - jq
  - NetworkManager-fortisslvpn
  - NetworkManager-fortisslvpn-gnome
  - openfortivpn
  - openssh-server
  - p7zip
  - p7zip-plugins
  - podman
  - podman-compose
  - python3-envycontrol
  - steam
  - terraform
  - timeshift
  - tmux
  - tree
  - vim
  - xclip
  - xorg-x11-drv-nvidia-cuda
  - yt-dlp
  - zsh

flatpak_pkgs:
  - com.brave.Browser
  - com.discordapp.Discord
  - com.getpostman.Postman
  - com.google.Chrome
  - com.obsproject.Studio
  - com.slack.Slack
  - com.visualstudio.code
  - com.usebottles.bottles
  - in.srev.guiscrcpy
  - io.dbeaver.DBeaverCommunity
  - io.enpass.Enpass
  - io.github.celluloid_player.Celluloid
  - net.agalwood.Motrix
  - net.ankiweb.Anki
  - net.davidotek.pupgui2
  - net.lutris.Lutris
  - org.onlyoffice.desktopeditors