---

- name: Get Balena Etcher Package Latest Version URL
  ansible.builtin.shell: >
    curl -s "https://api.github.com/repos/balena-io/etcher/releases/latest" | egrep -o 'https.*x86_64.rpm'
  register: url_rpm_etcher