---
- name: Get Github Packages
  include_tasks: github_packages.yml

- name: Install Extra Repositories from DNF 
  ansible.builtin.dnf:
    name: "{{ item.repo }}"
    state: present
    disable_gpg_check: "{{ item.disable_gpg_check }}"
  loop: "{{ repo_extra_dnf }}"

- name: Enable Hashicorp Repository
  ansible.builtin.command: dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo

- name: Enable Envycontrol COPR Repository
  ansible.builtin.command: dnf copr enable -y sunwire/envycontrol

- name: DNF Cache Update
  ansible.builtin.dnf:
    update_cache: yes

- name: Download Packages
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "/tmp/{{ item.name }}"
    mode: '0644'
  loop: "{{ pkgs_rpm }}"
  ignore_errors: true

- name: Install RPM Packages
  ansible.builtin.dnf:
    name: "/tmp/{{ item.name }}"
    state: present
    disable_gpg_check: yes
  loop: "{{ pkgs_rpm }}"
  ignore_errors: true

- name: Install Packages from Repository
  ansible.builtin.dnf:
    name: "{{ pkgs }}"
    state: latest
  ignore_errors: True

- name: Install vim-default-editor
  ansible.builtin.dnf:
    name: vim-default-editor
    state: latest
    allowerasing: yes
  ignore_errors: true

- name: Install Oh My Zsh!
  ansible.builtin.shell: >
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  become_user: "{{ ansible_env.SUDO_USER }}"
  tags: zsh

- name: Install Powerlevel10k ZSH Theme
  shell: >
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
  become_user: "{{ ansible_env.SUDO_USER }}"
  tags: zsh

- name: Change Default SHELL to ZSH
  ansible.builtin.user:
    name: "{{ ansible_env.SUDO_USER }}"
    shell: /usr/bin/zsh
  tags: zsh

- name: Install awscli v2
  ansible.builtin.shell: |
    wget -q -O "awscliv2.zip" https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    unzip awscliv2.zip
    bash -c './aws/install'
  args:
    executable: /bin/bash
    chdir: /tmp

- name: Flatpak - Add Flathub Repository
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: system

- name: Flatpak - Install Flathub Packages
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: system
  with_items: "{{ flatpak_pkgs }}"
  ignore_errors: true

- name: Upgrade Packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
  ignore_errors: true