---
- name: Include Task latest.yml
  include: url_rpm_latest.yml

- name: Update /etc/dnf/dnf.conf
  ansible.builtin.copy:
    src: dnf.conf
    dest: /etc/dnf
    owner: root
    group: root
    mode: '0644'

- name: Install Fedora Workstation Repository 
  ansible.builtin.dnf:
    name: fedora-workstation-repositories
    state: present

- name: Install Fedora Fusion Repository 
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm"
    - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm"

- name: Install Enpass Repository
  ansible.builtin.get_url:
    url: https://yum.enpass.io/enpass-yum.repo
    dest: /etc/yum.repos.d/enpass-yum.repo
    mode: '0644'
    owner: root

- name: Enable YUM Repositories
  ansible.builtin.command: dnf config-manager --set-enabled "{{ item }}"
  args:
    warn: false
  loop:
    - google-chrome
    - enpass

- name: DNF Cache Update
  ansible.builtin.dnf:
    update_cache: yes

- name: Download Packages
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "/tmp/{{ item.name }}"
    mode: '0644'
  loop: "{{ pkgs_rpm }}"

- name: Install RPM Packages
  ansible.builtin.dnf:
    name: "/tmp/{{ item.name }}"
    state: present
    disable_gpg_check: yes
  loop: "{{ pkgs_rpm }}"

- name: Install Packages from Repository
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: latest
  loop: "{{ pkgs }}"

- name: Install Oh My Zsh!
  ansible.builtin.shell: >
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  become_user: "{{ ansible_env.SUDO_USER }}"
  tags: zsh

- name: Change Default SHELL to ZSH
  ansible.builtin.user:
    name: "{{ ansible_env.SUDO_USER }}"
    shell: /usr/bin/zsh
  tags: zsh

- name: Flatpak - Add Flathub Repository
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: system

- name: Flatpak - Install Flathub Packages
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: system
  with_items: "{{ flatpak_pkgs }}"

- name: Upgrade Packages
  ansible.builtin.dnf:
    name: "*"
    state: latest