---

- name: Include Task latest.yml
  include: url_rpm_latest.yml

- name: Update /etc/dnf/dnf.conf
  copy:
    src: dnf.conf
    dest: /etc/dnf
    owner: root
    group: root
    mode: '0644'

- name: Install Fedora Workstation Repository 
  dnf:
    name: fedora-workstation-repositories
    state: present

- name: Install Enpass Repository
  get_url:
    url: https://yum.enpass.io/enpass-yum.repo
    dest: /etc/yum.repos.d/enpass-yum.repo
    mode: '0644'
    owner: root

- name: Enable Repositories
  dnf:
    enablerepo: "{{ item }}"
  loop:
    - google-chrome
    - enpass

- name: Disable Repositories
  dnf:
    disablerepo: rpmfusion-nonfree-nvidia-driver

- name: DNF Cache Update
  dnf:
    update_cache: yes

- name: Install Packages .rpm from URL
  dnf:
    name: "{{ item }}"
    state: latest
  loop: "{{ pkgs_urls }}"

- name: Install Packages from Repository
  apt:
    name: "{{ item }}"
    state: latest
  loop: "{{ pkgs }}"

- name: Install Oh My Zsh!
  shell: >
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  become_user: "{{ ansible_env.SUDO_USER }}"
  tags: zsh

- name: Change Default SHELL to ZSH
  user:
    name: "{{ ansible_env.SUDO_USER }}"
    shell: /usr/bin/zsh
  tags: zsh

- name: Add Flathub Flatpak Repository
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: system

- name: Flatpak | Install Flathub Packages
  flatpak:
    name: "{{ item }}"
    state: present
    method: system
  with_items: "{{ flatpak_pkgs }}"