---
- name: Uninstall Packages
  ansible.builtin.dnf:
    name: "{{ remove_pkgs }}"
    state: absent

- name: Disable Fedora Repositories
  ansible.builtin.command: dnf config-manager --set-disabled "{{ item }}"
  loop:
    - copr:copr.fedorainfracloud.org:phracek:PyCharm
    - google-chrome
    - rpmfusion-nonfree-nvidia-driver
    - rpmfusion-nonfree-steam